# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e648cdd694df531e5ec2d0215b74388da960160c95a17f6fe755090921342e1ffeb4fbfd1542303c50999379e383182a962401c383ab88b7138d95ee87562ee

test:
  secret_key_base: 347f8609fa6275f7f89246844fc87780a5ebc974342ca60d5f2933d5aeb2386d6cf545da30e27a2e1471fe5e03da61eb0f05549d3e0ca2e7a7ad71c629965ba9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
